import type { PermissionKey } from "./catalog";
import type { PermissionScope } from "@/app/generated/prisma/client";

/**
 * Quyền mặc định seed cho từng Role key (§21). Đây chỉ là điểm khởi đầu — Admin có
 * thể chỉnh lại qua trang Roles (roles.manage) sau khi seed.
 *
 * Ở Phase 1 mới chỉ có permission nhóm CORE nên phần lớn role không phải quản trị
 * chỉ có quyền đọc danh bạ tổ chức + thông báo của mình. Các phase sau (Work Hub,
 * Marketing, CRM...) sẽ mở rộng danh sách này theo vai trò tương ứng.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  SUPER_ADMIN: [
    "organization.manage",
    "users.read",
    "users.create",
    "users.update",
    "users.delete",
    "departments.read",
    "departments.create",
    "departments.update",
    "departments.delete",
    "teams.read",
    "teams.create",
    "teams.update",
    "teams.delete",
    "roles.read",
    "roles.manage",
    "audit_logs.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.delete",
    "task_templates.manage",
    "projects.read",
    "projects.create",
    "projects.update",
    "projects.delete",
    "workflows.read",
    "workflows.manage",
    "approvals.read",
    "approvals.manage",
    "leads.read",
    "leads.create",
    "leads.update",
    "leads.delete",
    "customers.read",
    "customers.create",
    "customers.update",
    "customers.delete",
    "orders.read",
    "orders.create",
    "orders.update",
    "orders.delete",
    "sales_catalog.manage",
    "warranty.read",
    "warranty.create",
    "warranty.update",
    "warranty.delete",
    "campaigns.read",
    "campaigns.create",
    "campaigns.update",
    "campaigns.delete",
    "content.read",
    "content.create",
    "content.update",
    "content.delete",
    "production.read",
    "production.create",
    "production.update",
    "production.delete",
    "channel_tracking.read",
    "channel_tracking.create",
    "channel_tracking.update",
    "channel_tracking.delete",
    "marketing_channels.read",
    "marketing_channels.manage",
    "ads.read",
    "ads.manage",
    "analytics.read",
    "analytics.manage",
    "ai.read",
    "ai.manage",
    "observability.read",
    "attendance.read",
    "attendance.manage",
    "leave_requests.create",
  ],
  ADMIN: [
    "organization.manage",
    "users.read",
    "users.create",
    "users.update",
    "users.delete",
    "departments.read",
    "departments.create",
    "departments.update",
    "departments.delete",
    "teams.read",
    "teams.create",
    "teams.update",
    "teams.delete",
    "roles.read",
    "roles.manage",
    "audit_logs.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.delete",
    "task_templates.manage",
    "projects.read",
    "projects.create",
    "projects.update",
    "projects.delete",
    "workflows.read",
    "workflows.manage",
    "approvals.read",
    "approvals.manage",
    "leads.read",
    "leads.create",
    "leads.update",
    "leads.delete",
    "customers.read",
    "customers.create",
    "customers.update",
    "customers.delete",
    "orders.read",
    "orders.create",
    "orders.update",
    "orders.delete",
    "sales_catalog.manage",
    "warranty.read",
    "warranty.create",
    "warranty.update",
    "warranty.delete",
    "campaigns.read",
    "campaigns.create",
    "campaigns.update",
    "campaigns.delete",
    "content.read",
    "content.create",
    "content.update",
    "content.delete",
    "production.read",
    "production.create",
    "production.update",
    "production.delete",
    "channel_tracking.read",
    "channel_tracking.create",
    "channel_tracking.update",
    "channel_tracking.delete",
    "marketing_channels.read",
    "marketing_channels.manage",
    "ads.read",
    "ads.manage",
    "analytics.read",
    "analytics.manage",
    "ai.read",
    "ai.manage",
    "observability.read",
    "attendance.read",
    "attendance.manage",
    "leave_requests.create",
  ],
  DIRECTOR: [
    "users.read",
    "departments.read",
    "teams.read",
    "roles.read",
    "audit_logs.read",
    "notifications.read",
    "tasks.read",
    "projects.read",
    "workflows.read",
    "approvals.read",
    "approvals.manage",
    "leads.read",
    "customers.read",
    "orders.read",
    "warranty.read",
    "campaigns.read",
    "content.read",
    "production.read",
    "channel_tracking.read",
    "marketing_channels.read",
    "ads.read",
    "analytics.read",
    "ai.read",
    "ai.manage",
    "observability.read",
    "attendance.read",
    "leave_requests.create",
  ],
  MANAGER: [
    "users.read",
    "departments.read",
    "teams.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "task_templates.manage",
    "projects.read",
    "projects.create",
    "projects.update",
    "workflows.read",
    "workflows.manage",
    "approvals.read",
    "leads.read",
    "customers.read",
    "orders.read",
    "warranty.read",
    "campaigns.read",
    "content.read",
    "production.read",
    "channel_tracking.read",
    "marketing_channels.read",
    "ads.read",
    "analytics.read",
    "ai.read",
    "ai.manage",
    "attendance.read",
    "leave_requests.create",
  ],
  // Trưởng nhóm: nhẹ hơn MANAGER (không quản lý được dự án/workflow, không có
  // ai.manage) — phụ trách công việc/chấm công của 1 Team. Lưu ý: hiện dùng scope
  // DEPARTMENT (xem DEFAULT_PERMISSION_SCOPES bên dưới) vì hệ thống scope hiện tại
  // chỉ có ALL/DEPARTMENT/OWN, chưa có scope riêng theo Team — với tổ chức hiện chỉ
  // có 1 Team/phòng ban thì không khác biệt, nhưng nếu sau này 1 phòng ban có nhiều
  // Team thì Trưởng nhóm sẽ thấy CẢ phòng ban chứ chưa lọc đúng theo Team — cần bổ
  // sung PermissionScope.TEAM + buildVisibilityScope riêng nếu cần chính xác hơn.
  TEAM_LEAD: [
    "users.read",
    "departments.read",
    "teams.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "projects.read",
    "approvals.read",
    "campaigns.read",
    "content.read",
    "production.read",
    "channel_tracking.read",
    "analytics.read",
    "ai.read",
    "attendance.read",
    "leave_requests.create",
  ],
  MARKETING_MANAGER: [
    "users.read",
    "departments.read",
    "teams.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "task_templates.manage",
    "projects.read",
    "projects.create",
    "projects.update",
    "workflows.read",
    "workflows.manage",
    "approvals.read",
    "leads.read",
    "campaigns.read",
    "campaigns.create",
    "campaigns.update",
    "campaigns.delete",
    "content.read",
    "content.create",
    "content.update",
    "content.delete",
    "production.read",
    "production.create",
    "production.update",
    "production.delete",
    "channel_tracking.read",
    "channel_tracking.create",
    "channel_tracking.update",
    "channel_tracking.delete",
    "marketing_channels.read",
    "marketing_channels.manage",
    "ads.read",
    "ads.manage",
    "analytics.read",
    "ai.read",
    "ai.manage",
    "attendance.read",
    "leave_requests.create",
  ],
  MARKETING_STAFF: [
    "users.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "projects.read",
    "approvals.read",
    "leads.read",
    "campaigns.read",
    "content.read",
    "content.create",
    "content.update",
    "production.read",
    "production.create",
    "production.update",
    "channel_tracking.read",
    "channel_tracking.create",
    "channel_tracking.update",
    "marketing_channels.read",
    "marketing_channels.manage",
    "ads.read",
    "analytics.read",
    "ai.read",
    "attendance.read",
    "leave_requests.create",
  ],
  SALES_MANAGER: [
    "users.read",
    "departments.read",
    "teams.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "task_templates.manage",
    "projects.read",
    "projects.create",
    "projects.update",
    "workflows.read",
    "workflows.manage",
    "approvals.read",
    "leads.read",
    "leads.create",
    "leads.update",
    "leads.delete",
    "customers.read",
    "customers.create",
    "customers.update",
    "customers.delete",
    "orders.read",
    "orders.create",
    "orders.update",
    "orders.delete",
    "sales_catalog.manage",
    "warranty.read",
    "warranty.create",
    "warranty.update",
    "warranty.delete",
    "campaigns.read",
    "content.read",
    "production.read",
    "channel_tracking.read",
    "analytics.read",
    "ai.read",
    "attendance.read",
    "leave_requests.create",
  ],
  SALES: [
    "users.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "projects.read",
    "approvals.read",
    "leads.read",
    "leads.create",
    "leads.update",
    "customers.read",
    "customers.create",
    "customers.update",
    "orders.read",
    "orders.create",
    "orders.update",
    "warranty.read",
    "warranty.create",
    "warranty.update",
    "campaigns.read",
    "content.read",
    "production.read",
    "channel_tracking.read",
    "analytics.read",
    "ai.read",
    "attendance.read",
    "leave_requests.create",
  ],
  CONTENT: [
    "users.read",
    "notifications.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "projects.read",
    "approvals.read",
    "campaigns.read",
    "content.read",
    "content.create",
    "content.update",
    "production.read",
    "production.create",
    "production.update",
    "channel_tracking.read",
    "channel_tracking.create",
    "channel_tracking.update",
    "marketing_channels.read",
    "marketing_channels.manage",
    "analytics.read",
    "ai.read",
    "attendance.read",
    "leave_requests.create",
  ],
  ANALYST: [
    "users.read",
    "departments.read",
    "teams.read",
    "audit_logs.read",
    "notifications.read",
    "tasks.read",
    "projects.read",
    "workflows.read",
    "approvals.read",
    "leads.read",
    "customers.read",
    "orders.read",
    "warranty.read",
    "campaigns.read",
    "content.read",
    "production.read",
    "channel_tracking.read",
    "marketing_channels.read",
    "ads.read",
    "analytics.read",
    "analytics.manage",
    "ai.read",
    "ai.manage",
    "observability.read",
    "attendance.read",
    "leave_requests.create",
  ],
  STAFF: ["users.read", "notifications.read", "tasks.read", "tasks.create", "tasks.update", "projects.read", "approvals.read", "ai.read", "attendance.read", "leave_requests.create"],
  VIEWER: [
    "users.read",
    "departments.read",
    "teams.read",
    "notifications.read",
    "tasks.read",
    "projects.read",
    "approvals.read",
    "leads.read",
    "customers.read",
    "orders.read",
    "warranty.read",
    "campaigns.read",
    "content.read",
    "production.read",
    "channel_tracking.read",
    "marketing_channels.read",
    "ads.read",
    "analytics.read",
    "ai.read",
    "attendance.read",
  ],
};

/**
 * Phase 10 — Scale: scope mặc định seed cho các permission trong `SCOPABLE_PERMISSIONS`
 * (lib/permissions/catalog.ts). Role không có entry ở đây (hoặc permission không có
 * entry) mặc định là ALL — đúng hành vi trước Phase 10 (mọi role có `tasks.read` thấy
 * toàn bộ task của tổ chức trên trang "Tất cả công việc").
 *
 * Quyết định: role cá nhân (đóng góp trực tiếp, không quản lý ai) → OWN, chỉ thấy
 * việc/lead của chính mình. Role Trưởng phòng → DEPARTMENT, thấy việc/lead của cả
 * phòng ban mình quản lý. Role giám sát toàn tổ chức (SUPER_ADMIN/ADMIN/DIRECTOR/
 * ANALYST/VIEWER) giữ ALL — đúng vai trò báo cáo/kiểm toán cần nhìn toàn cảnh.
 */
export const DEFAULT_PERMISSION_SCOPES: Record<string, Partial<Record<PermissionKey, PermissionScope>>> = {
  MANAGER: { "tasks.read": "DEPARTMENT", "attendance.read": "DEPARTMENT" },
  TEAM_LEAD: { "tasks.read": "DEPARTMENT", "attendance.read": "DEPARTMENT" },
  MARKETING_MANAGER: { "tasks.read": "DEPARTMENT", "leads.read": "DEPARTMENT", "attendance.read": "DEPARTMENT" },
  SALES_MANAGER: { "tasks.read": "DEPARTMENT", "leads.read": "DEPARTMENT", "attendance.read": "DEPARTMENT" },
  MARKETING_STAFF: { "tasks.read": "OWN", "leads.read": "OWN", "attendance.read": "OWN" },
  SALES: { "tasks.read": "OWN", "leads.read": "OWN", "attendance.read": "OWN" },
  CONTENT: { "tasks.read": "OWN", "attendance.read": "OWN" },
  STAFF: { "tasks.read": "OWN", "attendance.read": "OWN" },
};

export const ROLE_LABELS: Record<string, string> = {
  SUPER_ADMIN: "Quản trị tối cao",
  ADMIN: "Quản trị viên",
  DIRECTOR: "Giám đốc",
  MANAGER: "Trưởng phòng",
  TEAM_LEAD: "Trưởng nhóm",
  MARKETING_MANAGER: "Trưởng phòng Marketing",
  MARKETING_STAFF: "Nhân viên Marketing",
  SALES_MANAGER: "Trưởng phòng Kinh doanh",
  SALES: "Nhân viên Kinh doanh",
  CONTENT: "Nhân viên Content",
  ANALYST: "Phân tích dữ liệu",
  STAFF: "Nhân viên",
  VIEWER: "Chỉ xem",
};
